/*
 * Aineopintojen harjoitustyö: Ohjelmointi 2015 Kevät
 * Helsingin yliopisto Tietojenkäsittelytieteen laitos
 * Ooppa 2015 - GNU General Public License, version 3.
 */
package jtodo.ui;

/**
 * TODO: Created using Netbeans, will clean up later.
 * 
 * @author Ooppa
 */
public class TaskView extends javax.swing.JFrame {

    /**
     * Creates new form TaskView
     */
    public TaskView() {
        this.setTitle("jTODO");
        this.initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelForTasks = new javax.swing.JScrollPane();
        tableTasks = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        textfieldFilter = new javax.swing.JTextField();
        menubarMain = new javax.swing.JMenuBar();
        submenuFile = new javax.swing.JMenu();
        menuItemNewTasklist = new javax.swing.JMenuItem();
        menuItemSaveTasklist = new javax.swing.JMenuItem();
        menuItemLoadTasklist = new javax.swing.JMenuItem();
        submenuEdit = new javax.swing.JMenu();
        menuItemCheckboxAutosave = new javax.swing.JCheckBoxMenuItem();
        menuItemCheckboxAlwaysOnTop = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setName("mainframe"); // NOI18N

        scrollPanelForTasks.setName("scrollPanelForTasks"); // NOI18N

        tableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Compeleted", "Category", "Task Name", "Task Description", "Deadline"
            }
        ));
        tableTasks.setColumnSelectionAllowed(true);
        tableTasks.setName("tableTasks"); // NOI18N
        scrollPanelForTasks.setViewportView(tableTasks);
        tableTasks.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(scrollPanelForTasks, java.awt.BorderLayout.CENTER);

        bottomPanel.setName("bottomPanel"); // NOI18N
        bottomPanel.setLayout(new java.awt.BorderLayout());

        buttonAdd.setText("New Task");
        buttonAdd.setName("buttonAdd"); // NOI18N
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        bottomPanel.add(buttonAdd, java.awt.BorderLayout.LINE_START);

        textfieldFilter.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textfieldFilter.setText("Filter...");
        textfieldFilter.setBorder(null);
        textfieldFilter.setName("textfieldFilter"); // NOI18N
        textfieldFilter.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textfieldFilterCaretUpdate(evt);
            }
        });
        textfieldFilter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldFilterFocusGained(evt);
            }
        });
        textfieldFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldFilterActionPerformed(evt);
            }
        });
        bottomPanel.add(textfieldFilter, java.awt.BorderLayout.CENTER);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        menubarMain.setName("menubarMain"); // NOI18N

        submenuFile.setText("File");
        submenuFile.setName("submenuFile"); // NOI18N

        menuItemNewTasklist.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuItemNewTasklist.setText("New Tasklist");
        menuItemNewTasklist.setName("menuItemNewTasklist"); // NOI18N
        menuItemNewTasklist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewTasklistActionPerformed(evt);
            }
        });
        submenuFile.add(menuItemNewTasklist);

        menuItemSaveTasklist.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSaveTasklist.setText("Save Tasklist");
        menuItemSaveTasklist.setName("menuItemSaveTasklist"); // NOI18N
        menuItemSaveTasklist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveTasklistActionPerformed(evt);
            }
        });
        submenuFile.add(menuItemSaveTasklist);

        menuItemLoadTasklist.setText("Load Tasklist");
        menuItemLoadTasklist.setName("menuItemLoadTasklist"); // NOI18N
        menuItemLoadTasklist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLoadTasklistActionPerformed(evt);
            }
        });
        submenuFile.add(menuItemLoadTasklist);

        menubarMain.add(submenuFile);

        submenuEdit.setText("Edit");
        submenuEdit.setName("submenuEdit"); // NOI18N

        menuItemCheckboxAutosave.setSelected(true);
        menuItemCheckboxAutosave.setText("Autosave");
        menuItemCheckboxAutosave.setName("menuItemCheckboxAutosave"); // NOI18N
        menuItemCheckboxAutosave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCheckboxAutosaveActionPerformed(evt);
            }
        });
        submenuEdit.add(menuItemCheckboxAutosave);

        menuItemCheckboxAlwaysOnTop.setSelected(true);
        menuItemCheckboxAlwaysOnTop.setText("Always on top");
        menuItemCheckboxAlwaysOnTop.setName("menuItemCheckboxAlwaysOnTop"); // NOI18N
        menuItemCheckboxAlwaysOnTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCheckboxAlwaysOnTopActionPerformed(evt);
            }
        });
        submenuEdit.add(menuItemCheckboxAlwaysOnTop);

        menubarMain.add(submenuEdit);

        setJMenuBar(menubarMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCheckboxAlwaysOnTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCheckboxAlwaysOnTopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCheckboxAlwaysOnTopActionPerformed

    private void menuItemCheckboxAutosaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCheckboxAutosaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCheckboxAutosaveActionPerformed

    private void menuItemLoadTasklistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLoadTasklistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemLoadTasklistActionPerformed

    private void menuItemSaveTasklistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveTasklistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSaveTasklistActionPerformed

    private void menuItemNewTasklistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewTasklistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemNewTasklistActionPerformed

    private void textfieldFilterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldFilterFocusGained
        textfieldFilter.setText("");
    }//GEN-LAST:event_textfieldFilterFocusGained

    private void textfieldFilterCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textfieldFilterCaretUpdate
        // TODO
        System.out.println(textfieldFilter.getText());
    }//GEN-LAST:event_textfieldFilterCaretUpdate

    private void textfieldFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldFilterActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        TaskEditorWindow taskEditorWindow = new TaskEditorWindow(this);
    }//GEN-LAST:event_buttonAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JCheckBoxMenuItem menuItemCheckboxAlwaysOnTop;
    private javax.swing.JCheckBoxMenuItem menuItemCheckboxAutosave;
    private javax.swing.JMenuItem menuItemLoadTasklist;
    private javax.swing.JMenuItem menuItemNewTasklist;
    private javax.swing.JMenuItem menuItemSaveTasklist;
    private javax.swing.JMenuBar menubarMain;
    private javax.swing.JScrollPane scrollPanelForTasks;
    private javax.swing.JMenu submenuEdit;
    private javax.swing.JMenu submenuFile;
    private javax.swing.JTable tableTasks;
    private javax.swing.JTextField textfieldFilter;
    // End of variables declaration//GEN-END:variables
}
